

/**
 * splits the mammoth output file to multiple html files
 * run as "node dev/books/book-processor.js"
 * output is written to the new/books folder
 * 
 * use mammoth as below from the input directory
 * npx mammoth book-name.docx book-name.html --style-map=mammoth-styles.txt
 * 
 * DANGER - unless you absolutely have to do not reprocess existing docx files
 * since local corrections have been made to html files which would be overwritten
 * 
 */ 




// config/bookList.js

const isNodeEmpty = (node) => node.textElem.length == 0;

const getNodeFileName = (node) => `${node.ids.join("-")}.html`;

const bookList = [
  {
    name: "මහා මංගල සූත්‍රය ",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "mangala-suththa",
    cover: "books-png/mangala-suththa.png",
    group: 3,
    files: ["දොලොස්වල උදිතධීර හිමි", 2015, 2016],
    source: " ",
    featured: true,
    order: 6,

    output: "web",
    force: true,
  },
  {
    name: "ධර්මදේශනා පුහුණුව අංක 01 ",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "dharmadeshanapuhunuwa",
    cover: "books-png/dharmadeshanapuhunuwa.jpg",
    group: 1,
    files: ["දොලොස්වල උදිතධීර හිමි", 2013, 2014],
    source: " ",

    output: "web",
    force: true,

    featured: true,
    order: 2,
  },
  {
    name: "විතක්ක සූත්‍රය ",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "vithakka-suththa-01",
    cover: "books-png/vithakka-suththa-01.png",
    group: 3,
    files: ["දොලොස්වල උදිතධීර හිමි", 2017, 2018],
    source: " ",

    output: "web",
    force: true,
  },
  {
    name: "වුට්ඨි සූත්‍රය ",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "wutti-suththa-02",
    cover: "books-png/wutti-suththa-02.jpg",
    group: 3,
    files: ["දොලොස්වල උදිතධීර හිමි", 2019, 2020],
    source: " ",

    output: "web",
    force: true,
  },
  {
    name: "අද්ධා සූත්‍රය ",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "adda-suththa-03",
    cover: "books-png/adda-suththa-03.png",
    group: 3,
    files: ["දොලොස්වල උදිතධීර හිමි", 2021, 2022],
    source: " ",

    output: "web",
    force: true,
  },
  {
    name: "නිස්සරණිය සූත්‍රය ",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "nissaraniya-suththa-04",
    cover: "books-png/nissaraniya-suththa-04.png",
    group: 3,
    files: ["දොලොස්වල උදිතධීර හිමි", 2023, 2024],
    source: " ",

    output: "web",
    force: true,
  },
  {
    name: "සන්ති සූත්‍රය ",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "santhi-suththa-05",
    cover: "books-png/santhi-suththa-05.png",
    group: 3,
    files: ["දොලොස්වල උදිතධීර හිමි", 2025, 2026],
    source: " ",

    output: "web",
    force: true,
  },
  {
    name: "දහම් ගුණ",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "dhaham-guna-06",
    cover: "books-png/dhaham-guna-06.png",
    group: 3,
    files: ["දොලොස්වල උදිතධීර හිමි", 2026, 2027],
    source: " ",

    output: "web",
    force: true,
  },
  {
    name: "ලෝක සූත්‍රය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "loka-suththa-07",
    cover: "books-png/loka-suththa-07.png",
    group: 3,
    files: ["දොලොස්වල උදිතධීර හිමි", 2028, 2029],
    source: " ",

    output: "web",
    force: true,
  },
  {
    name: "පසන්න චිත්ත සූත්‍රය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "pasanna-chiththa suththa",
    cover: "books-png/pasanna-chiththa suththa.png",
    group: 3,
    files: ["දොලොස්වල උදිතධීර හිමි", 2030, 2031],
    source: " ",
    featured: true,
    order: 5,

    output: "web",
    force: true,
  },
  {
    name: "පදුට්ඨ පුද්ගල සූත්‍රය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "padutta-puggala-suththa",
    cover: "books-png/padutta-puggala-suththa.png",
    group: 3,
    files: ["දොලොස්වල උදිතධීර හිමි", 2032, 2033],
    source: " ",

    output: "web",
    force: true,
  },
  {
    name: "මිච්ඡාදිට්ඨි කම්ම සමාදාන සූත්‍රය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "michhaditti-kamma-samadana-suththa-06",
    cover: "books-png/michhaditti-kamma-samadana-suththa-06.png",
    group: 3,
    files: ["දොලොස්වල උදිතධීර හිමි", 2034, 2035],
    source: " ",

    output: "web",
    force: true,
  },
  {
    name: "චතුචක්ක සූත්‍රය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "chathchakka-suththa-09",
    cover: "books-png/chathchakka-suththa-09.png",
    group: 3,
    files: ["දොලොස්වල උදිතධීර හිමි", 2036, 2037],
    source: " ",

    output: "web",
    force: true,
  },
  {
    name: "නත්ථි පුත්ත  සූත්‍රය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "naththi-puththa-suththa-10",
    cover: "books-png/naththi-puththa-suththa-10.png",
    group: 3,
    files: ["දොලොස්වල උදිතධීර හිමි", 2038, 2039],
    source: " ",

    output: "web",
    force: true,
  },
  {
    name: "නන්දති සූත්‍රය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "nandathi-suththa-11",
    cover: "books-png/nandathi-suththa-11",
    group: 3,
    files: ["දොලොස්වල උදිතධීර හිමි", 2039, 2040],
    source: " ",

    output: "web",
    force: true,
  },
  {
    name: "ඵුසති සූත්‍රය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "pusathi-suththa-08",
    cover: "books-png/pusathi-suththa-08.png",
    group: 3,
    files: ["දොලොස්වල උදිතධීර හිමි", 2041, 2042],
    source: " ",

    output: "web",
    force: true,
  },
  {
    name: "පුරුස පියරූප සූත්‍රය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "purusa-piyarupa suththa12",
    cover: "books-png/purusa-piyarupa suththa12.png",
    group: 3,
    files: ["දොලොස්වල උදිතධීර හිමි", 2043, 2044],
    source: " ",

    output: "web",
    force: true,
  },

  {
    name: "උපසමානුස්සති භාවනාව",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "upasama-anussathiya",
    cover: "books-png/upasama-anussathiya.png",
    group: 4,
    files: ["දොලොස්වල උදිතධීර හිමි", 2046, 2047],
    source: " ",

    output: "web",
    force: true,
  },
  {
    name: "පංච උපාදානස්කන්ධය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "pancha-upadanaskandaya",
    cover: "books-png/pancha-upadanaskandaya.png",
    group: 1,
    files: ["දොලොස්වල උදිතධීර හිමි", 2048, 2049],
    source: " ",

    output: "web",
    force: true,
  },
  {
    name: "ඉරියාපත භාවනාව",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "iriyapatha-bhawanawa",
    cover: "books-png/iriyapatha-bhawanawa.png",
    group: 4,
    files: ["දොලොස්වල උදිතධීර හිමි", 2049, 2050],
    source: " ",

    output: "web",
    force: true,
  },
  {
    name: "චිත්තානුපස්සනාව",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "chiththanupassana",
    cover: "books-png/chiththanupassana.png",
    group: 4,
    files: ["දොලොස්වල උදිතධීර හිමි", 2051, 2052],
    source: " ",

    output: "web",
    force: true,
  },
  {
    name: "සතර අපාය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "atamaha-niraya",
    cover: "books-png/purusa-atamaha-niraya.png",
    group: 1,
    files: ["දොලොස්වල උදිතධීර හිමි", 2052, 2053],
    source: " ",
    featured: true,
    order: 3,

    output: "web",
    force: true,
  },
  {
    name: "ආර්ය අෂ්ටාංගික මාර්ගය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "arya-astangika -magga",
    cover: "books-png/arya-astangika -magga.png",
    group: 1,
    files: ["දොලොස්වල උදිතධීර හිමි", 2054, 2055],
    source: " ",

    output: "web",
    force: true,
  },
  {
    name: "ආනාපානසති භාවනාව",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "anapana-sathi-bhavana",
    cover: "books-png/anapana-sathi-bhavana.png",
    group: 4,
    files: ["දොලොස්වල උදිතධීර හිමි", 2055, 2056],
    source: " ",
    featured: true,
    order: 1,

    output: "web",
    force: true,
  },
  {
    name: "මා දුටු භාවනා යෝගීහු",
    author: " ",
    folder: "madutu-bhawana-yogiyo",
    cover: "books-png/madutu-bhawana-yogiyo.png",
    group: 5,
    files: [" ", 2057, 2058],
    source: " ",
    featured: true,
    order: 4,

    output: "web",
    force: true,
  },
  {
    name: "පඨම ආසව සූත්‍රය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "asrawa-suththa",
    cover: "books-png/asrawa-suththa.png",
    group: 3,
    files: ["දොලොස්වල උදිතධීර හිමි", 2058, 2059],
    source: " ",

    output: "web",
    force: true,
  },
  {
    name: "අට්ඨි පුඤ්ජ සූත්‍රය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "atti-punja-suththa",
    cover: "books-png/atti-punja-suththa.png",
    group: 3,
    files: ["දොලොස්වල උදිතධීර හිමි", 2060, 2061],
    source: " ",

    output: "web",
    force: true,
  },
  {
    name: "දාන සංවිභාග සූත්‍රය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "dana-sanvibaga-suththa",
    cover: "books-png/dana-sanvibaga-suththa.png",
    group: 3,
    files: ["දොලොස්වල උදිතධීර හිමි", 2062, 2063],
    source: " ",

    output: "web",
    force: true,
  },

  {
    name: "දුතිය භික්ඛු සූත්‍රය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "duthiya-bhikku-suththa",
    cover: "books-png/duthiya-bhikku-suththa.png",
    group: 3,
    files: ["දොලොස්වල උදිතධීර හිමි", 2064, 2065],
    source: " ",

    output: "web",
    force: true,
  },
  {
    name: "දුතිය සේඛ සූත්‍රය.",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "duthiya-bhikku-suththa",
    cover: "books-png/duthiya-bhikku-suththa.png",
    group: 3,
    files: ["දොලොස්වල උදිතධීර හිමි", 2066, 2067],
    source: " ",

    output: "web",
    force: true,
  },
  {
    name: "පඨම වේදනා සූත්‍රය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "patama-vedana-suththa",
    cover: "books-png/patama-vedana-suththa.png",
    group: 3,
    files: ["දොලොස්වල උදිතධීර හිමි", 2068, 2069],
    source: " ",

    output: "web",
    force: true,
  },
  {
    name: "පුඤ්ඤාභායී සූත්‍රය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "punyabai_suththa",
    cover: "books-png/punyabai_suththa.png",
    group: 3,
    files: ["දොලොස්වල උදිතධීර හිමි", 2069, 2070],
    source: " ",

    output: "web",
    force: true,
  },
  {
    name: "සබ්බ පරිඤ්ඤා සූත්‍රය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "sabba-parinna-suththa",
    cover: "books-png/sabba-parinna-suththa.png",
    group: 3,
    files: ["දොලොස්වල උදිතධීර හිමි", 2071, 2072],
    source: " ",

    output: "web",
    force: true,
  },
  {
    name: "සම්පජාන මුසාවාද සූත්‍රය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "sampajana-musawada-suththa",
    cover: "books-png/sampajana-musawada-suththa.png",
    group: 7,
    files: ["දොලොස්වල උදිතධීර හිමි", 2051, 2052],
    source: " ",

    output: "web",
    force: true,
  },
  {
    name: "උභෝ අත්ථ සූත්‍රය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "ubho-aththa-suththa",
    cover: "books-png/ubho-aththa-suththa.png",
    group: 7,
    files: ["දොලොස්වල උදිතධීර හිමි", 2051, 2052],
    source: " ",

    output: "web",
    force: true,
  },
  {
    name: "සබ්‍රහ්මක සූත්‍රය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "sabbrahmaka-suththa",
    cover: "books-png/sabbrahmaka-suththa.png",
    group: 7,
    files: ["දොලොස්වල උදිතධීර හිමි", 2053, 2054],
    source: "",

    output: "web",
    force: true,
  },
  {
    name: "සෝමනස්ස සූත්‍රය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "somanassa-suththa",
    cover: "books-png/somanassa-suththa.png",
    group: 7,
    files: ["දොලොස්වල උදිතධීර හිමි", 2055, 2056],
    source: "",

    output: "web",
    force: true,
  },
  {
    name: "අජිත සූත්‍රය ",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "ajitha-suththa",
    cover: "books-png/ajitha-suththa.png",
    group: 6,
    files: ["දොලොස්වල උදිතධීර හිමි", 2056, 2057],
    source: " ",

    output: "web",
    force: true,
  },
  {
    name: "බහූකාර සූත්‍රය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "bahikara-suththa",
    cover: "books-png/vbahikara-suththa.png",
    group: 7,
    files: ["දොලොස්වල උදිතධීර හිමි", 2058, 2059],
    source: " ",

    output: "web",
    force: true,
  },
  {
    name: "බ්‍රාහ්මණ සූත්‍රය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "bhahmana-suththa",
    cover: "books-png/bhahmana-suththa.png",
    group: 7,
    files: ["දොලොස්වල උදිතධීර හිමි", 2059, 2060],
    source: " ",

    output: "web",
    force: true,
  },
  {
    name: "ලෝකාවබෝධ සූත්‍රය ",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "lokawaboda-suththa",
    cover: "books-png/lokawaboda-suththa.png",
    group: 7,
    files: ["දොලොස්වල උදිතධීර හිමි", 2061, 2062],
    source: " ",

    output: "web",
    force: true,
  },
  {
    name: "දුතිය ජනකුහන සූත්‍රය ",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "dutiya-janakuhana-suththa",
    cover: "books-png/dutiya-janakuhana-suththa.png",
    group: 7,
    files: ["දොලොස්වල උදිතධීර හිමි", 2063, 2064],
    source: " ",

    output: "web",
    force: true,
  },
  {
    name: "පාපක සීල සූත්‍රය ",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "papaka-suththa",
    cover: "books-png/papaka-suththa.png",
    group: 7,
    files: ["දොලොස්වල උදිතධීර හිමි", 2064, 2065],
    source: " ",

    output: "web",
    force: true,
  },
  {
    name: "පඨම ජනකුහන සූත්‍රය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "patama-janakuhana-suththa",
    cover: "books-png/patama-janakuhana-suththa.png",
    group: 7,
    files: ["දොලොස්වල උදිතධීර හිමි", 2066, 2067],
    source: " ",

    output: "web",
    force: true,
  },
  {
    name: "සම්පන්න සීල සූත්‍රය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "sampanna-sila-suththa",
    cover: "books-png/sampanna-sila-suththa.png",
    group: 7,
    files: ["දොලොස්වල උදිතධීර හිමි", 2068, 2069],
    source: " ",

    output: "web",
    force: true,
  },
  {
    name: "තපනීය සූත්‍රය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "thapaniya-suththa",
    cover: "books-png/thapaniya-suththa.png",
    group: 7,
    files: ["දොලොස්වල උදිතධීර හිමි", 2070, 2071],
    source: " ",

    output: "web",
    force: true,
  },
  {
    name: "තිස්ස මෙත්තෙයිය සුත්තං",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "thissa-meththeyya-suththa",
    cover: "books-png/thissa-meththeyya-suththa.png",
    group: 6,
    files: ["දොලොස්වල උදිතධීර හිමි", 2072, 2073],
    source: " ",

    output: "web",
    force: true,
  },
  {
    name: "උපපරික්ඛ සූත්‍රය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "uparipakka-suththa",
    cover: "books-png/uparipakka-suththa.png",
    group: 7,
    files: ["දොලොස්වල උදිතධීර හිමි", 2074, 2075],
    source: " ",

    output: "web",
    force: true,
  },
  {
    name: "පුණ්ණක සූත්‍රය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "punnaka-suththa",
    cover: "books-png/punnaka-suththa.png",
    group: 6,
    files: ["දොලොස්වල උදිතධීර හිමි", 2076, 2077],
    source: "",

    output: "web",
    force: true,
  },
  {
    name: "සුක්ක ධම්ම සුත්තං",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "suska-dhamma",
    cover: "books-png/suska-dhamma.png",
    group: 7,
    files: ["දොලොස්වල උදිතධීර හිමි", 2078, 2079],
    source: "docx",

    output: "web",
    force: true,
  },
  {
    name: "භද්‍රාවුද සූත්‍රය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "bhaddrauda-suththa",
    cover: "books-png/bhaddrauda-suththa.png",
    group: 6,
    files: ["දොලොස්වල උදිතධීර හිමි", 2079, 2080],
    source: "docx",

    output: "web",
    force: true,
  },
  {
    name: "ජතු කණ්ණී සූත්‍රය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "chathu-kanni-suththa",
    cover: "books-png/chathu-kanni-suththa.png",
    group: 6,
    files: ["දොලොස්වල උදිතධීර හිමි", 2081, 2082],
    source: " ",

    output: "web",
    force: true,
  },
  {
    name: "කාම සූත්‍රය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "kama-suththa",
    cover: "books-png/kama-suththa.png",
    group: 6,
    files: ["දොලොස්වල උදිතධීර හිමි", 2083, 2084],
    source: "docx",

    output: "web",
    force: true,
  },
  {
    name: "කප්ප සූත්‍රය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "kappa-suttha",
    cover: "books-png/kappa-suttha.png",
    group: 6,
    files: ["දොලොස්වල උදිතධීර හිමි", 2085, 2086],
    source: "docx",

    output: "web",
    force: true,
  },
  {
    name: "සුභාෂිත සූත්‍රය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "subasitha-suththa",
    cover: "books-png/subasitha-suththa.png",
    group: 6,
    files: ["දොලොස්වල උදිතධීර හිමි", 2087, 2088],
    source: "docx",

    output: "web",
    force: true,
  },
  {
    name: "තෝදෙයිය සූත්‍රය.",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "thodeyya-suttha",
    cover: "books-png/thodeyya-suttha.png",
    group: 6,
    files: ["දොලොස්වල උදිතධීර හිමි", 2089, 2090],
    source: "docx",

    output: "web",
    force: true,
  },
  {
    name: "උරග සූත්‍රය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "uraga-suththa",
    cover: "books-png/uraga-suththa.png",
    group: 6,
    files: ["දොලොස්වල උදිතධීර හිමි", 2091, 2092],
    source: "docx",

    output: "web",
    force: true,
  },
  {
    name: "අනුබුද්ධ සූත්‍රය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "anubuddha-suththa-an",
    cover: "books-png/anubuddha-suththa-an.png",
    group: 8,
    files: ["දොලොස්වල උදිතධීර හිමි", 2093, 2094],
    source: "docx",

    output: "web",
    force: true,
  },
  {
    name: "අනුසෝත සූත්‍රය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "anusotha-suththa-an",
    cover: "books-png/anusotha-suththa-an.png",
    group: 8,
    files: ["දොලොස්වල උදිතධීර හිමි", 2095, 2096],
    source: "docx",

    output: "web",
    force: true,
  },
  {
    name: "චුන්ද සූත්‍රය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "chunda-suththa-suththanipatha",
    cover: "books-png/chunda-suththa-suththanipatha.png",
    group: 6,
    files: ["දොලොස්වල උදිතධීර හිමි", 2097, 2098],
    source: "docx",

    output: "web",
    force: true,
  },
  {
    name: "ධම්මනුධම්මපතිපථ සූත්‍රය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "dhammanudhammapatipaththi-suththa",
    cover: "books-png/dhammanudhammapatipaththi-suththa.png",
    group: 7,
    files: ["දොලොස්වල උදිතධීර හිමි", 2099, 2100],
    source: "docx",

    output: "web",
    force: true,
  },
  {
    name: "දුතියඛත සූත්‍රය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "duthiya-katha-suththa-an",
    cover: "books-png/duthiya-katha-suththa-an.png",
    group: 8,
    files: ["දොලොස්වල උදිතධීර හිමි", 2101, 2102],
    source: "docx",

    output: "web",
    force: true,
  },

  {
    name: "හේමක සූත්‍රය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "hemaka-suththa-suththanipatha",
    cover: "books-png/hemaka-suththa-suththanipatha.png",
    group: 6,
    files: ["දොලොස්වල උදිතධීර හිමි", 2103, 2104],
    source: "docx",

    output: "web",
    force: true,
  },
  {
    name: "මෙත්තගු සූත්‍රය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "meththagu-suththa-suththanipatha",
    cover: "books-png/meththagu-suththa-suththanipatha.png",
    group: 6,
    files: ["දොලොස්වල උදිතධීර හිමි", 2105, 2106],
    source: "docx",

    output: "web",
    force: true,
  },
  {
    name: "මෝගරාජ සූත්‍රය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "mogaraja-suththa-suththanipatha",
    cover: "books-png/mogaraja-suththa-suththanipatha.png",
    group: 6,
    files: ["දොලොස්වල උදිතධීර හිමි", 2107, 2108],
    source: "docx",

    output: "web",
    force: true,
  },
  {
    name: "නන්ද සූත්‍රය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "nanda-suththanipatha",
    cover: "books-png/nanda-suththanipatha.png",
    group: 6,
    files: ["දොලොස්වල උදිතධීර හිමි", 2109, 2110],
    source: "docx",

    output: "web",
    force: true,
  },
  {
    name: "පටම කථ සූත්‍රය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "patama-katha-suththa-an",
    cover: "books-png/patama-katha-suththa-an.png",
    group: 6,
    files: ["දොලොස්වල උදිතධීර හිමි", 2111, 2112],
    source: "docx",

    output: "web",
    force: true,
  },
  {
    name: "පොසාල සූත්‍රය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "posala-suththa-suththanipatha",
    cover: "books-png/posala-suththa-suththanipatha.png",
    group: 6,
    files: ["දොලොස්වල උදිතධීර හිමි", 2113, 2114],
    source: "docx",

    output: "web",
    force: true,
  },
  {
    name: "උදය සූත්‍රය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "udaya-suththa-suththanipatha",
    cover: "books-png/udaya-suththa-suththanipatha.png",
    group: 6,
    files: ["දොලොස්වල උදිතධීර හිමි", 2115, 2116],
    source: "docx",

    output: "web",
    force: true,
  },
  {
    name: "චතුත්ථ පටිපදා සූත්‍රය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "chathuththa-patipada-suththa-an",
    cover: "books-png/chathuththa-patipada-suththa-an.png",
    group: 8,
    files: ["දොලොස්වල උදිතධීර හිමි", 2116, 2117],
    source: "docx",

    output: "web",
    force: true,
  },
  {
    name: "චවන සූත්‍රය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "chawana-suththa-an",
    cover: "books-png/chawana-suththa-an.png",
    group: 8,
    files: ["දොලොස්වල උදිතධීර හිමි", 2118, 2119],
    source: "docx",

    output: "web",
    force: true,
  },
  {
    name: "දුක්ඛ සුත්තං",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "dukka-suththa-an",
    cover: "books-png/dukka-suththa-an.png",
    group: 8,
    files: ["දොලොස්වල උදිතධීර හිමි", 2120, 2121],
    source: "docx",

    output: "web",
    force: true,
  },
  {
    name: "දුතිය පීඨ විමාන වස්තුව",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "duthiya-pita-vimanavaththu-vm",
    cover: "books-png/duthiya-pita-vimanavaththu-vm.png",
    group: 9,
    files: ["දොලොස්වල උදිතධීර හිමි", 2122, 2123],
    source: "docx",

    output: "web",
    force: true,
  },
  {
    name: "දුතිය පුඤ්ඤාභිසන්ද සූත්‍රය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "duthiya-punnabisanda-suththa-an",
    cover: "books-png/duthiya-punnabisanda-suththa-an.png",
    group: 8,
    files: ["දොලොස්වල උදිතධීර හිමි", 2124, 2125],
    source: "docx",

    output: "web",
    force: true,
  },
  {
    name: "ගිහී සාමීචිපටිපදා සුත්තං",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "gihisamichipatipada-suththa-an",
    cover: "books-png/gihisamichipatipada-suththa-an.png",
    group: 8,
    files: ["දොලොස්වල උදිතධීර හිමි", 2126, 2127],
    source: "docx",

    output: "web",
    force: true,
  },
  {
    name: "ඉන්ද්‍රිය සුත්තං",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "indriya-suththa-an",
    cover: "books-png/indriya-suththa-an.png",
    group: 8,
    files: ["දොලොස්වල උදිතධීර හිමි", 2128, 2129],
    source: "docx",

    output: "web",
    force: true,
  },
  {
    name: "කාලකාරාම සූත්‍රය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "kalakarama-suththa-an",
    cover: "books-png/kalakarama-suththa-an.png",
    group: 8,
    files: ["දොලොස්වල උදිතධීර හිමි", 2130, 2131],
    source: "docx",

    output: "web",
    force: true,
  },
  {
    name: "කාම්බෝජ සූත්‍රය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "kamaboga-suththa-an",
    cover: "books-png/kamaboga-suththa-an.png",
    group: 8,
    files: ["දොලොස්වල උදිතධීර හිමි", 2132, 2133],
    source: "docx",

    output: "web",
    force: true,
  },
  {
    name: "කෝධගරු සූත්‍රය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "kroda-garu-suththa-an",
    cover: "books-png/kroda-garu-suththa-an.png",
    group: 8,
    files: ["දොලොස්වල උදිතධීර හිමි", 2134, 2135],
    source: "docx",

    output: "web",
    force: true,
  },
  {
    name: "පඤ්චම පටිපදා සුත්තං",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "panchama-patipada-suththa-an",
    cover: "books-png/panchama-patipada-suththa-an.png",
    group: 8,
    files: ["දොලොස්වල උදිතධීර හිමි", 2136, 2137],
    source: "docx",

    output: "web",
    force: true,
  },
  {
    name: "පඨම අග්ග සූත්‍රය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "patama-agga-suththa-an",
    cover: "books-png/patama-agga-suththa-an.png",
    group: 8,
    files: ["දොලොස්වල උදිතධීර හිමි", 2138, 2139],
    source: "docx",

    output: "web",
    force: true,
  },
  {
    name: "පටිපදා සූත්‍රය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "patipada-suththa-an",
    cover: "books-png/patipada-suththa-an.png",
    group: 8,
    files: ["දොලොස්වල උදිතධීර හිමි", 2140, 2141],
    source: "docx",

    output: "web",
    force: true,
  },
  {
    name: "සාරන්ද සූත්‍රය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "sarananda-suththa-an",
    cover: "books-png/sarananda-suththa-an.png",
    group: 8,
    files: ["දොලොස්වල උදිතධීර හිමි", 2142, 2143],
    source: "docx",

    output: "web",
    force: true,
  },
  {
    name: "සේඛබල විත්ථත සුත්තං",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "sekabala-viththatha-suththa-an",
    cover: "books-png/sekabala-viththatha-suththa-an.png",
    group: 8,
    files: ["දොලොස්වල උදිතධීර හිමි", 2144, 2145],
    source: "docx",

    output: "web",
    force: true,
  },
  {
    name: "සුප්පාවාස සූත්‍රය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "suppawasa-suththa-an",
    cover: "books-png/suppawasa-suththa-an.png",
    group: 8,
    files: ["දොලොස්වල උදිතධීර හිමි", 2146, 2147],
    source: "docx",

    output: "web",
    force: true,
  },
  {
    name: "තතිය පටිපදා සූත්තං",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "thathiya-patipada-suththa-an",
    cover: "books-png/thathiya-patipada-suththa-an.png",
    group: 8,
    files: ["දොලොස්වල උදිතධීර හිමි", 2148, 2149],
    source: "docx",

    output: "web",
    force: true,
  },
  {
    name: "උග්ගහ සුත්තං",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "ugga-suththa-an",
    cover: "books-png/ugga-suththa-an.png",
    group: 8,
    files: ["දොලොස්වල උදිතධීර හිමි", 2150, 2151],
    source: "docx",

    output: "web",
    force: true,
  },
  {
    name: "උපක්ලේස සූත්‍රය",
    author: "දොලොස්වල උදිතධීර හිමි",
    folder: "upakkilesa-suththa-an",
    cover: "books-png/upakkilesa-suththa-an.png",
    group: 8,
    files: ["දොලොස්වල උදිතධීර හිමි", 2152, 2153],
    source: "docx",

    output: "web",
    force: true,
  }
];


module.exports = {
  bookList,
  isNodeEmpty,
  getNodeFileName,
};
